spring.application.name=studynotes-ai

#openai.api.key=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

groq.api.key=( add you key here )
